workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      xcode: latest
    
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      
      - name: Generate Xcode project
        script: xcodegen generate
      
      - name: Build for Simulator
        script: |
          xcodebuild build \
            -project ColivingFinder.xcodeproj \
            -scheme ColivingFinder \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - /tmp/xcodebuild_logs/*.log

  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ai.e6.colivingfinder
      xcode: latest
    
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      
      - name: Generate Xcode project
        script: xcodegen generate
      
      - name: Build
        script: |
          xcodebuild build \
            -project ColivingFinder.xcodeproj \
            -scheme ColivingFinder \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
