name: Outpost
options:
  bundleIdPrefix: ai.e6
  deploymentTarget:
    iOS: "17.0"
targets:
  Outpost:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: data
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.e6.outpost
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "2"
        GENERATE_INFOPLIST_FILE: "YES"
        SWIFT_VERSION: "5.9"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "We use your location to find co-living spaces near you."
        INFOPLIST_KEY_CFBundleDisplayName: "Outpost"
